In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace = True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size = 0.2)

In [ ]:
scaler = StandardScaler()

In [ ]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train

array([[ 0.54698989,  0.09326464,  0.49417138, ...,  0.55946265,
        -0.37781167, -1.09885935],
       [ 3.96270337, -0.18699385,  3.96545661, ...,  0.67271837,
        -1.93757804, -1.57447683],
       [-0.66439686, -0.47437756, -0.69198817, ..., -0.92705644,
        -0.17700343, -0.1421068 ],
       ...,
       [-0.50552647, -0.17036835, -0.53775453, ..., -0.4610469 ,
         0.1405538 , -0.65855455],
       [-0.51971132, -0.65013289, -0.53035131, ..., -0.42812724,
        -0.42762457, -0.42460813],
       [-1.53648185, -0.81401285, -1.49071281, ..., -0.1502732 ,
         0.05182457,  0.98845028]])

In [ ]:
y_train

75     M
212    M
399    B
155    B
498    M
      ..
250    M
442    B
107    B
74     B
114    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
y_test

329    M
140    B
200    B
8      M
459    B
      ..
302    M
348    B
289    B
102    B
508    B
Name: diagnosis, Length: 114, dtype: object

In [ ]:
encoder = LabelEncoder()

In [ ]:
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,

In [ ]:
x_train_tensor = torch.from_numpy(x_train)
y_train_tensor = torch.from_numpy(y_train)
x_test_tensor = torch.from_numpy(x_test)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
y_train_tensor.shape

torch.Size([455])

#Defining the mode

In [ ]:
class MySimpleNN():
  def __init__(self, x):
    self.weights = torch.rand(x.shape[1], 1, dtype = torch.float64, requires_grad = True)
    self.bias = torch.zeros( 1, dtype = torch.float64, requires_grad = True)

  def forward(self , x):
    z = torch.matmul(x, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred


  def loss_function(self, y_pred, y):
    # clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    #calculate loss
    loss = -(y_train_tensor + torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

#Important parameters

In [ ]:
learning_rate = 0.1
epochs = 25

#Training pipeling

In [ ]:
model = MySimpleNN(x_train_tensor)
#definen loop
for epoch in range(epochs):
  #forward pass
  y_pred = model.forward(x_train_tensor)
  # print(y_pred)

  #loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)
  # print(f'Epoch : {epoch+1}, Loss : {loss.item()}')


  #backward pass
  loss.backward()


  #parametes update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch : {epoch + 1}, loss : {loss.item()}')



Epoch : 1, loss : 5.617275722592857
Epoch : 2, loss : 5.203899614155055
Epoch : 3, loss : 4.778753192378314
Epoch : 4, loss : 4.345874100707188
Epoch : 5, loss : 3.9096642514536297
Epoch : 6, loss : 3.4792880560246786
Epoch : 7, loss : 3.0617908537981933
Epoch : 8, loss : 2.6629715528574867
Epoch : 9, loss : 2.2840060738738988
Epoch : 10, loss : 1.9453517555539388
Epoch : 11, loss : 1.6625942056013403
Epoch : 12, loss : 1.4410532312343094
Epoch : 13, loss : 1.2788775029186217
Epoch : 14, loss : 1.1655114547113843
Epoch : 15, loss : 1.0871069900181434
Epoch : 16, loss : 1.031787468249932
Epoch : 17, loss : 0.991109440167801
Epoch : 18, loss : 0.9597324855321334
Epoch : 19, loss : 0.9345382929402952
Epoch : 20, loss : 0.9137277111804614
Epoch : 21, loss : 0.8962021294043826
Epoch : 22, loss : 0.8812314364493832
Epoch : 23, loss : 0.8682942463141836
Epoch : 24, loss : 0.8570009590212557
Epoch : 25, loss : 0.8470533005837639


In [ ]:

model.weights

tensor([[0.3758],
        [0.0013],
        [0.1009],
        [0.0096],
        [0.8001],
        [0.1450],
        [0.4833],
        [0.0439],
        [0.0161],
        [0.1454],
        [0.1618],
        [0.8297],
        [0.2972],
        [0.2167],
        [0.9469],
        [0.7287],
        [0.9786],
        [0.0517],
        [0.9273],
        [0.8915],
        [0.1073],
        [0.1454],
        [0.5873],
        [0.1020],
        [0.1837],
        [0.2919],
        [0.7740],
        [0.3822],
        [0.7652],
        [0.6838]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

# Evaluation

In [ ]:
with torch.no_grad():
  y_pred = model.forward(x_train_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy : {accuracy.item()}')

# print(y_pred)

Accuracy : 0.45614033937454224
