In [3]:
import torch
print(torch.__version__)

2.9.0+cu126


In [4]:
if torch.cuda.is_available():
  print("GPU availavle")
  print(f"using GPU: {torch.cuda.get_device_name()}")
else:
  print("GPU not available")

GPU availavle
using GPU: Tesla T4


##creating tensors

In [5]:
torch.empty(2, 3) # memory allocate karta hai

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#check type
a = torch.empty(4, 3)

In [7]:
type(a)

torch.Tensor

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(4, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(3, 4 )

tensor([[0.5086, 0.2259, 0.5857, 0.2643],
        [0.5356, 0.3485, 0.7568, 0.7027],
        [0.3069, 0.8383, 0.1627, 0.6584]])

In [11]:
torch.manual_seed(100)
torch.rand(3, 4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

In [12]:
torch.manual_seed(100)
torch.rand(3, 4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

In [13]:
torch.tensor([[1, 2, 3, 4, 5]])

tensor([[1, 2, 3, 4, 5]])

In [14]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
torch.linspace(0, 10, 11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [17]:
torch.full((3, 3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

##Tensors Shape


In [18]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x.size()

torch.Size([2, 3])

In [19]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
torch.empty_like(x)

tensor([[         224645,               0,               0],
        [            129, 139936052321616,       920093904]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

##Tensors DataType

In [24]:
x.dtype

torch.int64

In [25]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.tensor([1, 2, 3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [27]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

##Mathematical Operations

In [28]:
x = torch.rand(2, 3)

In [29]:
x + 2

tensor([[2.2239, 2.3023, 2.1784],
        [2.8238, 2.5557, 2.9770]])

In [30]:
x*5

tensor([[1.1195, 1.5117, 0.8921],
        [4.1192, 2.7787, 4.8851]])

In [31]:
x/7

tensor([[0.0320, 0.0432, 0.0255],
        [0.1177, 0.0794, 0.1396]])

In [32]:
x*100

tensor([[22.3894, 30.2346, 17.8419],
        [82.3844, 55.5744, 97.7024]])

In [33]:
x**4

tensor([[0.0025, 0.0084, 0.0010],
        [0.4607, 0.0954, 0.9112]])

In [34]:
a = torch.rand(4, 5)
b = torch.rand(4, 5)
print(a)
print(b)

tensor([[0.4440, 0.9478, 0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472, 0.7909, 0.4235],
        [0.0169, 0.2209, 0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359, 0.6476, 0.3430]])
tensor([[0.3182, 0.5261, 0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278, 0.4563, 0.3389],
        [0.6211, 0.5530, 0.6896, 0.3687, 0.9053],
        [0.8356, 0.3039, 0.6726, 0.5740, 0.9233]])


In [35]:
a+b

tensor([[0.7623, 1.4739, 0.7891, 1.0016, 1.1476],
        [1.2992, 0.9727, 0.9750, 1.2471, 0.7624],
        [0.6380, 0.7739, 1.6431, 1.0751, 1.0681],
        [1.7258, 0.8202, 0.7085, 1.2216, 1.2663]])

In [36]:
d = a-b
d

tensor([[ 0.1258,  0.4218,  0.6998, -0.0231, -0.6625],
        [ 0.1015,  0.0827, -0.4806,  0.3346,  0.0846],
        [-0.6042, -0.3321,  0.2639,  0.3377, -0.7424],
        [ 0.0546,  0.2124, -0.6367,  0.0737, -0.5803]])

In [37]:
a*b

tensor([[0.1413, 0.4986, 0.0332, 0.2506, 0.2195],
        [0.4194, 0.2348, 0.1799, 0.3608, 0.1435],
        [0.0105, 0.1222, 0.6576, 0.2605, 0.1474],
        [0.7438, 0.1569, 0.0241, 0.3717, 0.3167]])

In [38]:
c = b/a

In [39]:
torch.abs(d)

tensor([[0.1258, 0.4218, 0.6998, 0.0231, 0.6625],
        [0.1015, 0.0827, 0.4806, 0.3346, 0.0846],
        [0.6042, 0.3321, 0.2639, 0.3377, 0.7424],
        [0.0546, 0.2124, 0.6367, 0.0737, 0.5803]])

In [40]:
torch.round(d)

tensor([[ 0.,  0.,  1., -0., -1.],
        [ 0.,  0., -0.,  0.,  0.],
        [-1., -0.,  0.,  0., -1.],
        [ 0.,  0., -1.,  0., -1.]])

In [41]:
torch.ceil(d)

tensor([[1., 1., 1., -0., -0.],
        [1., 1., -0., 1., 1.],
        [-0., -0., 1., 1., -0.],
        [1., 1., -0., 1., -0.]])

In [42]:
torch.floor(d)

tensor([[ 0.,  0.,  0., -1., -1.],
        [ 0.,  0., -1.,  0.,  0.],
        [-1., -1.,  0.,  0., -1.],
        [ 0.,  0., -1.,  0., -1.]])

In [43]:
torch.clamp(d, min=2, max = 3)

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])

#Reduction Operation

In [44]:
e = torch.randint(size=(2, 3), low=0, high = 10, dtype = torch.float32)
e

tensor([[3., 8., 8.],
        [3., 3., 5.]])

In [45]:
torch.sum(e)

tensor(30.)

In [46]:
torch.sum(e, dim=0)

tensor([ 6., 11., 13.])

In [47]:
torch.sum(e, dim=1)

tensor([19., 11.])

In [48]:
torch.mean(e)

tensor(5.)

In [49]:
torch.prod(e)

tensor(8640.)

In [50]:
torch.std(e)

tensor(2.4495)

In [51]:
torch.var(e)

tensor(6.)

In [52]:
torch.argmax(e)

tensor(1)

In [53]:
torch.argmin(e)

tensor(0)

In [54]:
torch.argmin(e)

tensor(0)

In [55]:
f = torch.randint(size= (2, 3), low = 0 , high = 10)
g = torch.randint(size= (3, 3), low = 0 , high = 10)

In [56]:
print(f)
print(g)

tensor([[0, 6, 4],
        [0, 8, 4]])
tensor([[7, 2, 3],
        [8, 5, 6],
        [2, 9, 5]])


In [57]:
torch.transpose(f, 0, 1)

tensor([[0, 0],
        [6, 8],
        [4, 4]])

In [58]:
torch.det(g)

RuntimeError: linalg.det: Expected a floating point or complex tensor as input. Got Long

In [59]:
z = torch.randint(size= (3, 3), low = 0 , high = 10)

In [60]:
torch.log(z)

tensor([[  -inf, 1.3863, 0.6931],
        [1.9459, 0.0000, 0.0000],
        [1.6094, 1.3863, 1.3863]])

In [61]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

In [64]:
m.relu_()

tensor([[0.1780, 0.3011, 0.1893],
        [0.9186, 0.2131, 0.3957]])

In [63]:
print(id(m))

139936001940032


In [65]:
torch.cuda.is_available()

True

In [66]:
device = torch.device('cuda')

In [68]:
torch.rand((2, 3), device = device)   ##ab yeh gpu pe ban rahah hai

tensor([[0.8344, 0.7001, 0.5361],
        [0.8883, 0.0220, 0.7938]], device='cuda:0')

In [72]:
a = torch.rand(2, 3)
a

tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]])

In [73]:
a.to(device)

tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]], device='cuda:0')

In [74]:
b = a.to(device)

In [75]:
a

tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]])

In [76]:
b

tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]], device='cuda:0')

In [77]:
b + 10

tensor([[10.5887, 10.7340, 10.8497],
        [10.9112, 10.4847, 10.9436]], device='cuda:0')

In [78]:
import time

In [80]:
cpu1 = torch.rand(10000, 10000)
cpu2 = torch.rand(10000, 10000)
start = time.time()
result = torch.matmul(cpu1, cpu2)
end = time.time()
print(f"time taken si {end-start}")

time taken si 25.158754348754883


In [82]:
gpu1 = cpu1.to(device)
gpu2 = cpu2.to(device)
start = time.time()
result = torch.matmul(gpu1, gpu2)
end = time.time()
print(f"time taken si {end-start}")

time taken si 0.1407308578491211


In [83]:
print(f"gpu is {25.158754348754883/0.1407308578491211} times faster than cpu")

gpu is 178.772123848828 times faster than cpu


In [84]:
a = torch.ones(4, 4)

In [85]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [86]:
a.reshape(2, 8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [87]:
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [88]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [93]:
b = torch.rand(2, 3, 4)
b


tensor([[[0.0121, 0.0662, 0.3254, 0.6391],
         [0.1906, 0.6926, 0.0684, 0.8257],
         [0.4575, 0.6158, 0.6166, 0.1433]],

        [[0.7931, 0.7799, 0.3788, 0.2750],
         [0.3103, 0.1942, 0.4751, 0.9200],
         [0.0472, 0.5397, 0.7160, 0.2801]]])

In [91]:
b.permute(2, 1, 0).shape

torch.Size([4, 3, 2])

In [92]:
b.permute(2, 1, 0)

tensor([[[0.2436, 0.3151],
         [0.4549, 0.7766],
         [0.4926, 0.9847]],

        [[0.1008, 0.6987],
         [0.8776, 0.9718],
         [0.7323, 0.6817]],

        [[0.1176, 0.7903],
         [0.3721, 0.5460],
         [0.4682, 0.2420]],

        [[0.3651, 0.5187],
         [0.7827, 0.9329],
         [0.4369, 0.6212]]])

In [94]:
#unsqueeze
#image size

c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [95]:
c.unsqueeze(0)

tensor([[[[0.6461, 0.9829, 0.0332],
          [0.6062, 0.9161, 0.5627],
          [0.7324, 0.0059, 0.0328],
          ...,
          [0.9668, 0.1475, 0.1551],
          [0.7547, 0.5301, 0.4456],
          [0.4881, 0.3709, 0.4450]],

         [[0.1055, 0.4676, 0.4169],
          [0.0405, 0.7130, 0.7065],
          [0.7563, 0.5052, 0.7200],
          ...,
          [0.4334, 0.4535, 0.3271],
          [0.2623, 0.5784, 0.7117],
          [0.2122, 0.6586, 0.0986]],

         [[0.6939, 0.9907, 0.6002],
          [0.9364, 0.3266, 0.3991],
          [0.4966, 0.5163, 0.3171],
          ...,
          [0.2783, 0.9312, 0.9582],
          [0.4273, 0.0127, 0.5916],
          [0.8864, 0.1996, 0.9992]],

         ...,

         [[0.4488, 0.2129, 0.3067],
          [0.9904, 0.0693, 0.3989],
          [0.8134, 0.7213, 0.6952],
          ...,
          [0.3618, 0.4892, 0.9806],
          [0.3722, 0.7582, 0.4191],
          [0.0836, 0.6446, 0.2381]],

         [[0.3302, 0.7567, 0.6654],
          [0.8416

In [96]:
d = torch.rand(1, 20)
d.squeeze(0).shape

torch.Size([20])

In [97]:
import numpy as np

In [98]:
a = torch.tensor([1, 2, 3])

In [99]:
a

tensor([1, 2, 3])

In [100]:
a.numpy()

array([1, 2, 3])

In [101]:
b = np.array([2, 3, 4, 5])
b

array([2, 3, 4, 5])

In [102]:
torch.from_numpy(b)

tensor([2, 3, 4, 5])

In [2]:
import torch
x = torch.tensor([2, 3, 4, 5, 6])

In [3]:
x

tensor([2, 3, 4, 5, 6])

In [4]:
x.view(-1, 1)

tensor([[2],
        [3],
        [4],
        [5],
        [6]])

In [5]:
x

tensor([2, 3, 4, 5, 6])

In [7]:
y = x.view(-1)

In [8]:
y

tensor([2, 3, 4, 5, 6])

In [9]:
y[2] = 8

In [10]:
y

tensor([2, 3, 8, 5, 6])

In [11]:
x

tensor([2, 3, 8, 5, 6])