##pytorch-nn-module

In [2]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)   #out represent z

    return out

##Create Dataset


In [22]:
features = torch.rand(10, 5)


# create model
model = Model(features.shape[1])

# call the model
# model.forward(features)
model(features)

tensor([[0.4238],
        [0.4290],
        [0.4124],
        [0.3948],
        [0.3959],
        [0.4282],
        [0.4032],
        [0.4142],
        [0.3948],
        [0.4183]], grad_fn=<SigmoidBackward0>)

In [11]:
# getting model weights
# model.linear.weight
model.linear.bias

Parameter containing:
tensor([0.4364], requires_grad=True)

In [12]:
!pip install torchinfo

In [13]:
from torchinfo import summary
summary(model, input_size = (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [14]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)   #out represent z
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [25]:
features = torch.rand(10, 5)


# create model
model = Model(features.shape[1])

# call the model
# model.forward(features)
model(features)

tensor([[0.4416],
        [0.4682],
        [0.4832],
        [0.4602],
        [0.4282],
        [0.4643],
        [0.4466],
        [0.4554],
        [0.4485],
        [0.4244]], grad_fn=<SigmoidBackward0>)

In [16]:
# getting model weights
model.linear1.weight
# model.linear.bias

Parameter containing:
tensor([[ 0.0299, -0.1868, -0.3574, -0.2115,  0.1069],
        [ 0.4020,  0.3483,  0.1027,  0.2951,  0.4327],
        [ 0.4390, -0.2792, -0.1078, -0.2728, -0.3824]], requires_grad=True)

In [17]:
from torchinfo import summary
summary(model, input_size = (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [18]:
from torch.nn.modules import ReLU
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out



In [19]:
features = torch.rand(10, 5)


# create model
model = Model(features.shape[1])

# call the model
model.forward(features)
model(features)

tensor([[0.4546],
        [0.5247],
        [0.5277],
        [0.5534],
        [0.5426],
        [0.4817],
        [0.4591],
        [0.5426],
        [0.5154],
        [0.5003]], grad_fn=<SigmoidBackward0>)

In [21]:
# getting model weights
# model.linear1.weight
# model.linear.bias

##Practice


In [27]:
import torch
import torch.nn as nn
from torchinfo import summary


In [37]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 16)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(16, 16)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

features = torch.rand(728, 16)

model = Model(features.shape[1])

model(features)

tensor([[0.4618, 0.5098, 0.5291,  ..., 0.5787, 0.4482, 0.4582],
        [0.4404, 0.5312, 0.5109,  ..., 0.5547, 0.4248, 0.4607],
        [0.4394, 0.5201, 0.5186,  ..., 0.5566, 0.4322, 0.4596],
        ...,
        [0.4594, 0.5126, 0.5090,  ..., 0.5634, 0.4480, 0.4507],
        [0.4647, 0.5157, 0.5276,  ..., 0.5698, 0.4456, 0.4571],
        [0.4513, 0.5112, 0.5349,  ..., 0.6063, 0.4672, 0.4283]],
       grad_fn=<SigmoidBackward0>)

In [40]:
# summary(model, input_size=(728, 16))

In [43]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 16),
        nn.ReLU(),
        nn.Linear(16, 16),
        nn.ReLU(),
        nn.Linear(16, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

features = torch.rand(728, 16)

model = Model(features.shape[1])

model(features)

tensor([[0.5181],
        [0.5217],
        [0.5218],
        [0.5187],
        [0.5225],
        [0.5218],
        [0.5255],
        [0.5181],
        [0.5242],
        [0.5221],
        [0.5180],
        [0.5272],
        [0.5260],
        [0.5213],
        [0.5235],
        [0.5230],
        [0.5217],
        [0.5300],
        [0.5173],
        [0.5270],
        [0.5216],
        [0.5280],
        [0.5207],
        [0.5212],
        [0.5266],
        [0.5288],
        [0.5231],
        [0.5158],
        [0.5141],
        [0.5183],
        [0.5238],
        [0.5189],
        [0.5191],
        [0.5303],
        [0.5256],
        [0.5260],
        [0.5214],
        [0.5158],
        [0.5269],
        [0.5246],
        [0.5279],
        [0.5193],
        [0.5274],
        [0.5235],
        [0.5184],
        [0.5268],
        [0.5114],
        [0.5184],
        [0.5201],
        [0.5186],
        [0.5273],
        [0.5216],
        [0.5275],
        [0.5232],
        [0.5193],
        [0

In [44]:
summary(model, input_size=(728, 16))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [728, 1]                  --
├─Sequential: 1-1                        [728, 1]                  --
│    └─Linear: 2-1                       [728, 16]                 272
│    └─ReLU: 2-2                         [728, 16]                 --
│    └─Linear: 2-3                       [728, 16]                 272
│    └─ReLU: 2-4                         [728, 16]                 --
│    └─Linear: 2-5                       [728, 1]                  17
│    └─Sigmoid: 2-6                      [728, 1]                  --
Total params: 561
Trainable params: 561
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.41
Input size (MB): 0.05
Forward/backward pass size (MB): 0.19
Params size (MB): 0.00
Estimated Total Size (MB): 0.24